### ISSUE TITLE
Shared and x86 legalizations interfere for `bnot`

### ISSUE THREAD

**Issue by abrown** [CraneStation/cranelift#1092]
To support Wasm SIMD's `v128.not` operation I decided to legalize `bnot` to a `vconst + bxor`:

```
ebb0(v0: b32x4):
    v1 = bnot v0
    ; check: v2 = vconst.b32x4 0xffffffffffffffffffffffffffffffff
    ; nextln: v1 = bxor v2, v0
    return v1
```

However, I legalized this in the x86 legalizations, which I believe is causing some issues with the shared legalizations:

```
STALLED for 3 seconds with 32/98 tests finished
slow: filetests/isa/x86/legalize-isplit-backwards.clif
thread 'main' panicked at 'worker threads stalled for 10 seconds.', cranelift-filetests/src/runner.rs:283:21
```

I think c66e1b6292272580628f5c2b7aaa918e5c40dd7b is the change that introduces the legalization for splitting and joining `i128s`. @bjorn3, @bnjbvr: what is the best way to add my legalization and not break the existing legalization?

**Comment by bjorn3** [comment]
Does that one actually apply to vectors? `isplit` and `iconcat` should only work on scalars right?

**Comment by bnjbvr** [comment]
At the moment, custom legalizations are supposed final, that is: they can't fail and will do the right thing in all the cases. So if we have a custom legalization for an opcode but it doesn't do anything (based on input type or something), since legalization will restart at the first newly inserted instruction (in case it introduced other instructions that need legalization), this will result in an infinite loop. Is this what's happening here?

If so, one workaround would be to call the next custom legalization in line in the higher precedence custom legalization. A better, long-term fix would be to make custom legalization return a boolean indicating if they succeeded or not.
