### ISSUE TITLE
Inconsistency between comment and implementation in constant_hash.rs

### ISSUE THREAD

**Issue by walac** [CraneStation/cranelift#1095]
The [comment](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/meta/src/constant_hash.rs#L11) says the hash table is quadratically probed but [the code](https://github.com/CraneStation/cranelift/blob/master/cranelift-codegen/meta/src/constant_hash.rs#L33) implements linear probe.

@bnjbvr `git blame` told me you implemented the hash table, I would like to fix it, which one is correct?

**Comment by bnjbvr** [comment]
Thanks for opening an issue. Since the **step** augments linearly, if H is the computed hash value, this means that the second item will be in H + 1, then H + 3 (= H + 1 + 2), then H + 6 (= H + 1 + 2 + 3), so it's really a quadratic probe, since the step is in `H + (i * (i - 1)) / 2` for the i-th value, which is a quadratic probe. Does it make sense to you too?

**Comment by walac** [comment]
Ah, yeah, I missed that, thanks for taking the time to explain it.
