### ISSUE TITLE
Optimize `0.0` constants

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#317]
Cretonne currently lowers all floating-point constant instructions by emitting integer constants with the desired bit patterns and then moving them into floating-point registers. The code that does this is [here](https://github.com/cretonne/cretonne/blob/master/lib/codegen/src/legalizer/mod.rs#L245).

For reference, the `expand_fconst` function used here is registered [here](https://github.com/cretonne/cretonne/blob/master/lib/codegen/meta/base/legalize.py#L78).

However, most CPUs have faster ways to set registers to zero. For example, on x86, one can do `xorps %xmm0, %xmm0`. Xor'ing a register with itself seems roundabout, but it turns out to be common enough that CPUs recognize it specially, and often optimize it in register renaming rather than actually executing it as an instruction.

A simple way to implement this for x86 would be to define an encoding rule for x86 similar to the rules for [integer constants](https://github.com/cretonne/cretonne/blob/master/lib/codegen/meta/isa/x86/encodings.py#L189), using an `instp` predicate to test for the value of 0. Be aware that in IEEE 754 floating-point, negative zero compares equal to zero, but is a distinct bit pattern; the [`is_sign_positive`](https://doc.rust-lang.org/std/primitive.f64.html#method.is_sign_positive) function may be useful in distinguishing between the two.

Cretonne has encodings for xorps:
https://github.com/cretonne/cretonne/blob/master/lib/codegen/meta/isa/x86/encodings.py#L595
https://github.com/cretonne/cretonne/blob/master/lib/codegen/meta/isa/x86/recipes.py#L332
which may be useful examples, though the recipe as written is only usable for `Binary` operators, so I think the best way to proceed here is to add a new recipe.

Here's a simple testcase for f32:
```
function %foo() -> f32 fast {
ebb0:
    v0 = f32const 0.0
    return v0
}
```

**Comment by data-pup** [comment]
This issue looks really neat, I would love to try and take care of this. If you have any other advice, feel free to send it my way :)

**Comment by sunfishcode** [comment]
Sounds good!

The first step here is to define a recipe in lib/codegen/meta/isa/x86/recipes.py. Above I linked to another recipe that uses xorps but does so for `Binary` operators. So you'll need to make a similar recipe, but for `UnaryImm` operators, with no declared register inputs, that uses its output register for the x86 instruction encoding inputs. And of course, please ask questions if anything is unclear, from the x86 encoding bits to the python DSL bits.

**Comment by sunfishcode** [comment]
This is implemented in #344!

**Comment by rpjohnst** [comment]
Would it be worth doing this for integers as well? `xor eax, eax` is smaller than `mov eax, 0`.

**Comment by lars-t-hansen** [comment]
> Would it be worth doing this for integers as well? `xor eax, eax` is smaller than `mov eax, 0`.

Been wondering that myself but haven't had time to look up the relevant optimization advice / research it properly.

**Comment by iximeow** [comment]
`xor x, x` is pretty common from gcc/llvm/etc at least, but... the question about relevant optimization advice made me second guess my assumption that it would be equivalent or faster. Actual behavior of course depends on the specific architecture but Agner Fog's microarchitecture manual happens to specifically mention `xor x, x` being treated well under section 9.8 (page 127, `Instructions that need no execution unit`). That's in reference to Sandy Bridge in particular but is repeated for some subsequent architectures.

If we're concerned about squeezing out performance on Pentium II era chips, there's also a mention in section 6.8 (page 83) that setting a register to zero with `mov` won't prevent a partial register stall in some situations where a zeroing via `xor` or `sub` would. There's also some weirdness about dependency chains there that make `mov` useful where `xor` isn't, but I suspect that's not the intended Cranelift audience either way.

I wonder if saving four instruction bytes for each `mov reg, 0` might be a better performance improvement just because it's shorter. :)

That all said, if it makes sense for integers as well, I'd like to take a shot at the change - I've been wanting to learn how that fits together in Cranelift for a little bit now.

**Comment by julian-seward1** [comment]
It (the xor %r, %r thing) is a standard recommendation.  See section 3.5.1.8 "Clearing Registers and Dependency Breaking Idioms" in https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf.

**Comment by sunfishcode** [comment]
Indeed, we should do this for integers as well. Integer wasn't as urgent as for floating-point, because floating-point constants are more expensive to materialize, however it's still worth doing. And now, the floating-point version can serve as an example of how to to it :-).
