### ISSUE TITLE
Jump Tables

### ISSUE THREAD

**Issue by sunfishcode** [CraneStation/cranelift#318]
Codegen currently legalizes `br_table` instructions by [lowering them to sequences of branches](https://github.com/cretonne/cretonne/blob/master/lib/codegen/src/legalizer/mod.rs#L187). What we want is to use actual jump tables.

This will require some new `binemit` capabilities, for emitting the actual jump table data, outside of the function body.

In theory, the `RelocSink` trait has support for relocating jump tables (`reloc_jt`), however as this hasn't been tested, it may need to be modified or extended.

A jump table is an array, and the elements can be either absolute addresses or offsets relative to some base, often the base of the jump table itself. PIC prefers relative offsets, so we should start with that, and do absolute offsets later if extra speed for non-PIC is needed. Using a jump table typically involves a bounds-check to see if the `br_table` index is in bounds, and then an indexed load into the table using the `br_table` index. In the case of a relative offset, the base is then added to the result. Then, the final result can be used as the operand to an indirect jump.

**Comment by Amanieu** [comment]
A form of branch relaxation (#73) also applies to PIC jump tables: the offset from the table base can be encoded as `i8`, `i16` or `i32` depending on how far the targets are from the table.

**Comment by tyler** [comment]
I've started working a bit on this and wanted to put some thoughts here and gather feedback.

Alright, so sementically there are few steps to implementing a jump_table with Cranelift.

1. Bounds check the the value indexing the jump table.
2. Load the address from the jump table.
3. Check that the destination address is not "empty", as our jump tables are sparse.
4. Jump indirectly using that address.

So, an expansion of this:

```
function u0:0(i64) -> i64 system_v {
    jt0 = jump_table ebb1, 0, ebb2

ebb0(v0: i64):
    br_table v0, jt0
    ...

ebb1: ...
ebb2: ...
}
```

Might look something like this:

```
function u0:0(i64) -> i64 system_v {
    jt0 = jump_table ebb1, 0, ebb2

ebb0(v0: i64):
    v1 = ifcmp_imm v0, 3
    brif uge v7, ebb3

    v2 = load_address_from_jump_table v0, jt0   # v2 is an integer type
    v3 = ifcmp_imm v2, 0
    brif eq v3, ebb3

    indirect_jump v2


ebb3: (fallthrough target)

ebb1: ...
ebb2: ...
}
```

I don't really like that, because it would require us to make the address loaded from the jump table a non-opaque value, so it can be checked against zero. An alternative would be to fill in the sparse slots of the jump table with the destination address... But that is complicated by the fact that a jump table can be used from multiple locations within a function.

If we could ensure that a jump table was only used once in a function it would be nice to be able to shorten that to:

```
function u0:0(i64) -> i64 system_v {
    jt0 = jump_table ebb1, 0, ebb2

ebb0(v0: i64):
    v1 = ifcmp_imm v0, 3
    brif uge v7, ebb3

    v2 = load_address_from_jump_table v0, jt0   # v2 is an opaque address type
    indirect_jump v2

ebb3: (fallthrough target)

ebb1: ...
ebb2: ...
}
```

Regardless, though, the `load_address_from_jump_table` will also likely need to expand into a few instructions, at least on x86-64. We'll need to load the base address of the jump table, and then calculate the offset from that.

As for where the jump tables end up, I'd love input on how that should work. My inclination is to make it so that they're appended directly to the end of the machine code for the function they're defined in. But there might be reasons not to do that that I'm not aware of. 

Anyway, it's possible that I'm thinking about this all wrong. So please adjust my thinking. :)

**Comment by tyler** [comment]
I retract the part about opaque values as I now realize we're doing similar things in several other places, but the point still remains that we'd need check the jump table slots for "empty" placeholders.

**Comment by sunfishcode** [comment]
Your thinking makes sense to me :-). I'll also observe that Wasm jump tables are always fully dense, so it doesn't need us to worry about this, for its part. So, one option is to just make it a validation error if the front-end leaves gaps in the table, and then we don't have to worry about them. That's pretty tempting, actually, especially as a first step here.

Beyond wasm, I'm hoping we'll eventually have a helper library for people translating switches which might be sparse (also mentioned [here](https://github.com/CraneStation/cranelift/issues/432#issuecomment-408720631)), and such a library could take care of filling in table gaps with explicit branch targets, so we may not need anything more in the back end.

Appending jump tables to the machine code for their containing function will work on x86, and that might be ok for now. In the future though, on eg. ARM it may be harder because smaller instruction immediate fields may mean the jump table can't be as far away from the code that uses it. It's tempting to pass in *another* "Sink" object for this, but we already have a lot of Sinks, and we're already talking about more. So brainstorming, what if we just added a method to the `CodeSink` trait which declared "I'm done with the code now, and am starting the jump tables", so that `CodeSink` implementations can put jump tables in different places if needed?

**Comment by tyler** [comment]
Alright alright. I'll enforce the dense table requirement then. And go from there. Thanks!

**Comment by camilstaps** [comment]
Can I ask what the current status of this issue is? It is not exactly clear to me what #453 exactly accomplished and whether this is being worked on actively. I'm looking at the x86 code generated for a ~750 entries WebAssembly branch table and this is still split up in a sequence of branches. Also, looking at the amount of code that had to be touched for #453 I'm assuming this isn't really a good first issue? Thanks in advance for any pointers.

**Comment by sunfishcode** [comment]
With #453 merged, this is now implemented!

**Comment by sunfishcode** [comment]
Note that this also adds a setting, "jump_tables_enabled", to allow jump tables to be disabled, in which case codegen currently falls back to conditional branches.
