### ISSUE TITLE
Issue with regmove/regspill/regfill encodings

### ISSUE THREAD

**Issue by lachlansneff** [CraneStation/cranelift#420]
Using the latest version of cranelift, I get this error when debug assertions are turned on:

```
panicked at 'assertion failed: `(left == right)`
  left: `68`,
 right: `64`: Invalid registers for REX-less Op1 encoding', /Users/lachlansneff/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-codegen-0.17.0/src/isa/x86/binemit.rs:74:5
```

**Comment by sunfishcode** [comment]
Are you able to capture the IR that this happens on? Or, do you have the wasm this happens on?

**Comment by lachlansneff** [comment]
Here's the dumped ir of the function that crashes cranelift.

https://gist.github.com/lachlansneff/b0909afd608b6effe379e1f4f33b418a

**Comment by sunfishcode** [comment]
Thanks!

It looks like the bug is that a `regfill` is getting optimized to a REX-less encoding, even though it uses %r11, because `regfill` is one of the special register allocation instructions in which its locations aren't normal operands or results, so they aren't getting taken into account when an encoding is picked. This is not the first bug we've had with `regfill` and friends being special, so I'm thinking about whether we can restructure the code to more comprehensively avoid such problems.

A workaround is to disable optimizations, as with `opt_level=fastest`.

**Comment by sunfishcode** [comment]
I've now pushed c658871142371675ce2adbbb7641c85b1f060652, which works around this bug in cranelift's own code, which is a nicer workaround than requiring users to use `opt_level=fastest`. I'm leaving this issue open for now, as we should really fix the underlying bug.

**Comment by lachlansneff** [comment]
Fantastic, thanks.

**Comment by sunfishcode** [comment]
I currently have two possible approaches in mind here.

One is to revise the coloring pass to avoid using regmove/regspill/regfill altogether, and instead just keep track of temporary register reassignments in side tables.

Another is to let the coloring pass use these instructions as it does now, but introduce a rewrite pass after spilling which eliminates regmove/regspill/regfill by rewriting the instructions to their actual encodings.

Either way, the goal would be that we wouldn't have any regmove/regspill/regfill instructions left after register allocation, so that any code that wants to run really late can just examine the `locations` array to see where values are allocated, without having to maintain a `RegDiversions`.

**Comment by sunfishcode** [comment]
And actually, the above is what #500 is all about, so I think we can close this issue and just track the remaining work there.
