### ISSUE TITLE
Question: How close is CraneLift to being a usable rustc backend?

### ISSUE THREAD

**Issue by nicoburns** [CraneStation/cranelift#508]
I'm eagerly awaiting faster Rust build times, and a key part of that seems like it might be replacing LLVM with something faster for debug builds. I know this is something that is on the radar for this project, but I'm wondering how actively this is being worked on, and roughly what kind of timescale you could imagine this happening on (if it does in fact happen).

For example, might it be realistic to have a CraneLift backend for Rust on x86-64 working by the end of 2019?

**Comment by sunfishcode** [comment]
There are actually two different efforts that I'm aware of, taking different approaches. One of them is starting by refactoring the Rust backend, so that we can share much of the LLVM backend code with a Cranelift backend; the current PR is [here](https://github.com/rust-lang/rust/pull/54012). And the other is writing an entirely new backend, which is [here](https://github.com/bjorn3/rustc_codegen_cranelift). So I'm optimistic that we'll have something :-).

The biggest unknowns right now are in the support for specific OS's and configurations. For example, Windows poses several unique challenges, so it's unclear how that'll proceed.

**Comment by sunfishcode** [comment]
Thanks for the question! Feel free to re-open this or file a new issue if you have any further questions.
