### ISSUE TITLE
Legalization for fcvt_from_sint not applied when specified

### ISSUE THREAD

**Issue by bjorn3** [CraneStation/cranelift#535]
Could be related to it having two type vars.

See https://github.com/bjorn3/cretonne/tree/wip_legalize_fcvt_from_sint for repro.

**Comment by bnjbvr** [comment]
Hi @bjorn3 ! Could you please explain a bit more what's going on? Is there any chance you could make a minimal clif test case that would help reproducing this issue, please? Thanks!

**Comment by bjorn3** [comment]
In https://github.com/bjorn3/cretonne/commit/3f6ef1ec5a785efd691c036f6db7c2046dd7b6e5 a legalization is defined for this instruction, but the test case (from the same commit) in which it should be applied, it isnt applied.

**Comment by bnjbvr** [comment]
I looked at it a bit, and I think I understand what's going on:

- the legalization is defined in the shared legalization group `widen`.
- this group is used in x86 for instructions which controlling type variable is i8 or i16
- fcvt_from_sint controlling type variable is the result type, hence f32 or f64

So the legalization is basically inaccessible! (and if you look at the generated `encodings-x86.rs` file, it doesn't seem to reference this legalization at all)

Since the x86 legalization group is chained with the expand_flags one, which itself is chained with the expand one, one way to do it would be to move these legalizations to the `expand` group. I find it myself a bit confusing, but I am generally unsure of the decision criteria for whether a legalization should be present in the widen or expand group.

**Comment by bjorn3** [comment]
Makes sense!

**Comment by bnjbvr** [comment]
@bjorn3 please let us know if this fixes your problem, so we can close the issue, or maybe rebrand it. (Maybe we should emit a warning or abort compilation when this kind of situation happens, since it should be detectable when running the meta program.)

**Comment by bjorn3** [comment]
I will submit a PR for the legalization of this instruction soon.
