### ISSUE TITLE
Cranelift-generated code has better performance than firefox's optimizing compiler.

### ISSUE THREAD

**Issue by lachlansneff** [CraneStation/cranelift#566]
In [this](https://hacks.mozilla.org/2018/10/webassemblys-post-mvp-future/) recently released article from mozilla, one can find this gem:

> In addition, we’re working on a new optimizing compiler called Cranelift. Cranelift is designed to compile code quickly, in parallel at a function by function level. At the same time, the code it generates gets even better performance than our current optimizing compiler.

This is really great news! The performance of wasm compiled by cranelift is already top-notch... and there are still a number of ways it can get better!

Well done everyone!

**Comment by bnjbvr** [comment]
Oops, unfortunately it seems the original intent was to be more hypothetical and looking ahead of what it is *designed* to be; you can see that other paragraphs express this intent better. Currently, benchmarking against IonMonkey (the highly optimizing engine in Firefox) is a bit unfair, because it is the result of years of optimization by a large team of developers, while Cranelift can still be considered to be in its infancy. There's a lot of hope we can do better than Ion in the future, though, if we do things the right way!

**Comment by lachlansneff** [comment]
:( Haha, oh well. It'll get there eventually.
