### ISSUE TITLE
Use cargo-nono in CI

### ISSUE THREAD

**Issue by hobofan** [CraneStation/cranelift#661]
Hey there!

I'm reaching out to check if cranelift might be interested in using [https://github.com/hobofan/cargo-nono](cargo-nono) in your CI build, in order to give better guarantees for the `no_std` support? As @sunfishcode mentioned using cargo-nono on cranelift in an issue there before, I thought that supporting cranelift in CI as well might be an interesting goal to work towards.

There are already a few issues that would need to be resolved for that use-case to work, but I'd be happy for more feedback:
- [ ] Provide binaries https://github.com/hobofan/cargo-nono/issues/18
- [ ] Make alloc-aware https://github.com/hobofan/cargo-nono/issues/20
- [ ] A panic I encountered when checking `cranelift-wasm` https://github.com/hobofan/cargo-nono/issues/22

Let me know what you think!

**Comment by sunfishcode** [comment]
The current idea is that `no_std` cranlelift is a fairly specialized thing that isn't being widely used yet, so until we start getting some traction with that feature, we don't want to burden our developers (most of whom don't need it) with supporting it. It's currently not a burden for me to just do `no_std` testing before I publish new versions to crates.io and fix up any issues that have crept in since the last release. However, this isn't a particularly deep thought, so I'd be interested if other people have other ideas on what's best to do here.

I had one random idea for cargo-nono though: rather than providing pre-built binaries (hobofan/cargo-nono#18), what if cargo-nono were able to be used as a [build-dependency] library? That might eliminate the need to separately `cargo install` it, which would eliminate one source of friction.

**Comment by hobofan** [comment]
Gotcha 👍 

> I had one random idea for cargo-nono though: rather than providing pre-built binaries (hobofan/cargo-nono#18), what if cargo-nono were able to be used as a [build-dependency] library? That might eliminate the need to separately cargo install it, which would eliminate one source of friction.

One of the main reasons for creating cargo-nono was this bug: https://github.com/hobofan/cargo-nono/issues/16. Adding cargo-nono to the build-dependencies would trigger that bug, and with that negate the whole purpose of it, so that wouldn't work....
Coincidentally I implemented the building of binaries via Travis just before I read your comment 😄

**Comment by sunfishcode** [comment]
Another random idea: I wonder if [wasmi](https://github.com/paritytech/wasmi) would be interested in integrating cargo-nono for testing [no_std support](https://github.com/paritytech/wasmi#no_std-support).

**Comment by bnjbvr** [comment]
Closing since there's no clear want to have this in CI right now, we can do this later. Thanks for opening an issue!
