### ISSUE TITLE
How can cranelift be realistically be competitive with llvm and GCC? 

### ISSUE THREAD

**Issue by LifeIsStrange** [CraneStation/cranelift#672]
There is a useful concept to the mind, the notion of order of magnitude.

This is not an apple to apple comparison, but here is noneless something that should alert the mind.
Cranelift is currently 2,337 commits versus 175, 218 commits for llvm.
76,135 for clang.
609 vs 58 contributors.
How can this project realistically compete in term of features or simply runtime performance when llvm had decade of Empirical optimisations and expertize from the hardware maker themselves?

To answer this question, either you say that you will bring more developers than llvm has, which if true would be pointless, why not redirect this workforce to improve the modular llvm directly instead of redundancy work #NIH syndrome.

Or you can say this compiler has a revolutionary, because evolutionary would NOT suffice to compete with the order of magnitude advantage that llvm has.
Either automatic parallelization or auto offloading to GPU, then why not make a new llvm passe like polly?

Either you say, Cranelift is not a project that aims to compete with llvm and GCC and thus gain real world usage, but is still interesting to make, to do research that could be backported to llvm, or is just fun.
And I would be happy to hear that.

**Comment by sunfishcode** [comment]
Cranelift doesn't have to do all the things that the LLVM project does, to be successful. Since you mention clang commits, one major example is that the Cranelift project has no desire to develop a new C++ frontend. Another major example is mid-level optimization -- while we have some ideas about things we might do in that space in the future (perhaps even something [very different](https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-705.pdf)), we aren't currently building a mid-level optimizer, and don't expect we'll need one just to meet our first round of goals -- WebAssembly compilation where the WebAssembly code has already been optimized (often by LLVM's optimizer), and Rust backend compilation focused on day-to-day development rather than on release builds.

There are many dimensions to compilers besides optimization; compile time, resource usage, unique features, or unique customization hooks are all ways for a compiler to make itself valuable. Cranelift has a very different internal architecture, which gives it some unique opportunities in these areas.

But even in the arena of optimization, the way humans build compilers are built [is changing](https://arxiv.org/abs/1809.02161). In the past, one of the major bodies of work for optimization was to have large teams of people over a long time assemble large manually-maintained and manually debugged libraries of hand-written pattern-match-and-replacement code. In the future, we expect superoptimizers will take over much of this work. Along the way, Cranelift may even use the same superoptimizers as LLVM, such as [Souper](https://github.com/google/souper).

**Comment by LifeIsStrange** [comment]
Thank you, the goal is clearer even if I have serious doubts about the capacity of superoptimizers to find as much interesting patterns as humans.

**Comment by LifeIsStrange** [comment]
The paper "Optimizing compilation with the
Value State Dependence Graph" seems very interesting!
Couldn't it be implemented on llvm?
But it's opensource your are indeed free to do as you desire :)

**Comment by sunfishcode** [comment]
Yes, one could implement a VSDG in LLVM too. One of the things that makes the idea intriguing for Cranelift is that if we're optimizing Rust code, and the frontend could give us memory dependence information up front based on Rust borrow rules, we might be able to construct a relatively precise dependence graph without a lot of work up front. VSDGs aren't cheap, so if we're going to do them, avoiding some of the setup costs seems appealing.
