### ISSUE TITLE
`function_builder.ins().f64const(32f64)` cause an error?

### ISSUE THREAD

**Issue by mokeyish** [CraneStation/cranelift#677]
I used the following code:
```rust
function_builder.ins().f64const(32f64)
```
and cause the error.
```
    |
190 |                 Ok(self.builder.ins().f64const(32f64))
    |                                       ^^^^^^^^ the trait `std::convert::From<f64>` is not implemented for `cranelift::prelude::Ieee64`
    |
    = note: required because of the requirements on the impl of `std::convert::Into<cranelift::prelude::Ieee64>` for `f64`
```

**Comment by bjorn3** [comment]
It seems that you need to pass a value of type [`Ieee64`](https://docs.rs/cranelift-codegen/0.28.0/cranelift_codegen/ir/immediates/struct.Ieee64.html) to `f64const`. You can create one using [`Ieee64::with_float`](https://docs.rs/cranelift-codegen/0.28.0/cranelift_codegen/ir/immediates/struct.Ieee64.html#method.with_float).

**Comment by mokeyish** [comment]
Is the implementation of  `std::convert::Into<cranelift::prelude::Ieee64>` for `f64` missing?

**Comment by sunfishcode** [comment]
Yeah. I believe it was omitted because of a general caution for implicit conversions on floating-point values, however Rust's general strictness about implicit conversions means we don't have to worry about f64's turning into f32's or i64's turning into f64's or other things, so allowing f64 to convert into Ieee64 seems safe.

So, I think it would be reasonable to add `Into` implementations for `Ieee64` and `Ieee32`, from f64 and f32 respectively. Would you be interested in submitting a PR for this?

**Comment by mokeyish** [comment]
Yes, I'm glad to submitting a PR for this.
