### ISSUE TITLE
Instructions for codegen with clif-util wasm?

### ISSUE THREAD

**Issue by jlb6740** [CraneStation/cranelift#710]
How do you use clif-util to create a target binary from WASM? I am looking at 

![image](https://user-images.githubusercontent.com/45402135/54780068-1c379500-4bd6-11e9-8ee9-6f4a68f3ed61.png)

but when I run the command on my wasm binary the best I can do is print the cranelift IR.  After trail and poking around the code I did see that I can set my target to x86_64 or i386 to run the following command 

`clif-util wasm -T -v -d -p --set opt_level=best --target=x86_64 -- multiply.wasm`

**Comment by bjorn3** [comment]
You should probably use [wasmtime](https://github.com/CraneStation/wasmtime) instead.

**Comment by jlb6740** [comment]
Hi .. thanks for the suggestion. Separately I am poking at wasmtime to understand what it is doing. But for clif-util is compiling to binary not possible? What does it mean to compile to the "target language" when the target is set to x86_64?

**Comment by pchickey** [comment]
clif-util doesnt know how to put x86_64 into executable memory, or into an ELF file, so that they can be easily executed. wasmtime takes care of this, and hook up the wasm imports to implementations, and expose the exports so you can run them. clif-util is really just to help Cranelift project developers inspect how Cranelift works and run automated test suites. There's nothing inside the Cranelift repo that is designed to actually execute the code it spits out.

**Comment by jlb6740** [comment]
Ok ... I see thanks a lot.
