### ISSUE TITLE
Structure of cranelift-wasm/src/translation_utils.rs causes many pointless heap allocations

### ISSUE THREAD

**Issue by julian-seward1** [CraneStation/cranelift#975]
@lars-t-hansen, @bnjbvr, @sunfishcode 
Using CL to compile wasm from Spidermonkey causes translation_utils.rs to allocate heap blocks which are never read from.  For compiling wasm_lua_binarytrees.js, it causes at least 3034 blocks of average size 44 bytes to be allocated, initialised, and thrown away.

The culprit is `fn blocktype_to_type` and possibly its friends.  It looks like this:
```
pub fn blocktype_to_type(ty: wasmparser::TypeOrFuncType) -> WasmResult<ir::Type> {
    match ty {
        wasmparser::TypeOrFuncType::Type(ty) => type_to_type(ty),
        wasmparser::TypeOrFuncType::FuncType(_) => {
            wasm_unsupported!("multi-value block signature {:?}", ty);
        }
    }
}
```
`WasmResult` is a parameterisation of plain `Result`.  In the `FuncType` case, `wasm_unsupported!` formats the specified string, allocating the result on the heap, and wraps it up (indirectly) in `Err(..)`.  That all sounds reasonable, except that the use point in SM looks like this:
```
if let Ok(ty_cre) = blocktype_to_type(*ty) {
    builder.append_ebb_param(if_not, ty_cre);
}
```
so the string allocated for the `Err` return is simply thrown away.

The obvious fix is to change the return type of `blocktype_to_type` (and friends) to be `Option`-like rather than `Err`-like.  But then we lose the ability to provide a string describing a failure to callers that actually want that.  So I'm not sure what to do.

**Comment by julian-seward1** [comment]
In C++ the obvious thing to do would be to overload `blocktype_to_type` on its return type, so that it could return either an `Option` or an `Err`.  If my Rust-foo were somewhat better it seems plausible that something similar could be hacked up with the use of traits.

**Comment by lars-t-hansen** [comment]
In this case I might split `blocktype_to_type` into two functions, one that returns an Option and another that is a helper, `blocktype_to_type_whynot`, and change the callers to call the latter in their else branches, if they care about the error.  Probably not fully general, but might be ok.  With a comment as to why.

Arguably the caller is buggy here since it ignores a possible error?

**Comment by julian-seward1** [comment]
Yeah, actually the `_whynot` (or perhaps `_why_failed`) scheme seems simpler in that it doesn't require a new trait.

**Comment by bjorn3** [comment]
Maybe extern `WasmError` with a variant storing only the return type itself.

**Comment by bnjbvr** [comment]
Agreed with Lars that the callers are wrong here; they should unwrap the result, otherwise we're silently treating wasm using the multi-value feature as if it were not using values. I wonder why this happens in the first place, since the benchmark you mentioned has been compiled way before multi-value was even proposed as a wasm extension...

**Comment by nox** [comment]
The callers are probably wrong, but I'm curious why `WasmError` is even the error type used here when the only error condition is that it is not yet implemented for some inputs.

I would do like this:

```rust
struct NotImplementedYet;

pub fn blocktype_to_type(ty: wasmparser::TypeOrFuncType) -> Result<ir::Type, NotImplementedYet>;
```

It is ok to have more than one error type per item/module/crate/workspace/project.

**Comment by acfoltzer** [comment]
This is partially my fault, as I introduced a `String` where there was previously a `&'static str` in `WasmResult` in order to provide more detailed info about what wasn't supported. It's nice to have that extra fidelity in error messages, but I didn't expect us to ever be creating them in a hot path. Rather I expected that if `wasm_unsupported!()` ever got evaluated, the whole compilation would be stopping rather soon.

I'm not very familiar with the code where `blocktype_to_type` is called, but I share the suspicions of others that ignoring this `Err` case is probably not the right thing to do. If it is correct, `blocktype_to_type` should probably just return an `Option` because that's the only way callers currently use it.

**Comment by julian-seward1** [comment]
@nox.  Wouldn't the `struct NotImplementedYet` proposal lose information?  I mean, currently a failure in these functions produces an `Err` holding info about the failure, including a string mentioning the problem, and the failing type.  `struct NotImplementedYet` seems to throw that away, but maybe I misunderstand.

**Comment by julian-seward1** [comment]
Lars' `_whynot` proposal doesn't work out as well as it seems at first, because there are a couple of places where the result of `*type_to_type` is fed to the `?` operator, and changing the type of the base function to return an `Option` breaks that.

In the end I returned to my original proposal, which is have two versions of each function, one returning an `Option` and one returning a `WasmResult`, and implement the latter by calling the former.  That works well and is not particularly ugly or intrusive.

**Comment by julian-seward1** [comment]
I should perhaps clarify: the problem affects all three: `type_to_type`, `tabletype_to_type` and ` blocktype_to_type`.  At some use points the error value is propagated onwards via the `?` operator, but in most cases it is ignored.

**Comment by bnjbvr** [comment]
Looking at this code a bit more, I think I get why there's this error:

- blocktype_to_type calls into type_to_type
- which yields an Err result when the type is Void, which definitely can happen for block types

So I think a most proper fix is to audit all the callers of type_to_type, and split this function into `type_to_maybe_void_type` (that'd return a `Result<Option<ir::Type>>`, `Ok(None)` when the type is void, `Ok(Some(T))` when the type is known by Cranelift, `Err` otherwise), and `type_to_nonvoid_type` (calling the first one, and converting `Ok(None)` into an error).

`Tabletype_to_type` doesn't have this issue because a table can't be void typed. `Blocktype_to_type` signature should be changed too. This will get us back into a situation where having an `Err` result is actually a failure, and not an edge case, so it should remove the bad memory usage around Error types here.

@julian-seward1 Does it sound reasonable to you, and is this something you'd like to investigate?

**Comment by julian-seward1** [comment]
@bnjbvr Thanks for the analysis.  Yes, certainly, I can investigate that.
